version: '2.1'

services:
  mongodb:
    image: mangoraft/mongodb-arm
    container_name: "mongodb"
    environment: 
      - MONGODB_PASS=geheim
    ports:
      - 27017:27017
  pollserver:
    image: tuttas/pollserver:arm
    ports:
      - 3000:3000
    links: 
      - mongodb
    environment: 
      - MONGODB=mongodb://admin:geheim@mongodb:27017
    depends_on: 
      - mongodb
  pollclient:      
    image: tuttas/pollclient:arm
    ports:
      - 81:80
      
