version: '2.1'

services:
  dbserver:
    image: dbserver
    build:
      context: .
      dockerfile: Dockerfile-mongoserver 
    ports:
      - 27017:27017
  pollserver:
    image: pollserver
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 3000:3000
  pollclient:
    image: pollclient
    build:
      context: .
      dockerfile: Dockerfile-Client
    ports:
      - 80:80
    links:
      - pollserver
