version: '2.1'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  pollserver:
    image: tuttas/pollserver:latest
    ports:
      - 3000:3000
    links: 
      - mongodb
    environment: 
      - MONGODB=mongodb://mongodb:27017
      - SECRET=12345
    depends_on: 
      - mongodb
  pollclient:      
    image: tuttas/pollclient:latest
    environment: 
      - POLLSERVER=http://localhost:3000/
      - SECRET=12345
    ports:
      - 81:80
      
