version: '2.1'

services:
  mongodb:
    image: mangoraft/mongodb-arm
    container_name: "mongodb"
    environment: 
      - MONGODB_PASS=geheim
    ports:
      - 27017:27017
  pollserver:
    image: tuttas/pollserver:arm
    ports:
      - 3000:3000
    links: 
      - mongodb
    environment: 
      - MONGODB=mongodb://admin:geheim@mongodb:27017
      - SECRET=12345
    depends_on: 
      - mongodb
  pollclient:      
    image: tuttas/pollclient:arm
    environment: 
      - POLLSERVER=http://192.168.178.74:3000/
      - SECRET=12345
    ports:
      - 81:80
      
